const menu = [
  {
    id: 1,
    title: "mahamris",
    category: "Snacks",
    price: 10,
    img: "./images/mahamri.jpg",
    desc: `Puffy and golden brown, these triangular doughnuts are made with coconut milk and spiced with cardamom. `,
  },
  {
    id: 2,
    title: "Cakes",
    category: "Snacks",
    price: 40,
    img: "./images/cakes.jfif",
    desc: `A cupcake is a small cake designed to serve one person, which may be baked in a small thin paper or aluminum cup. `,
  },
  {
    id: 3,
    title: "Toasted bread",
    category: "Snacks",
    price: 20,
    img: "./images/toastedbread.jpg",
    desc: `Grilled  bread over a moderately hot fire until lightly charred, about 1 minute per side.`,
  },
  {
    id: 4,
    title: "Chapatis",
    category: "Snacks",
    price: 20,
    img: "./images/chapatis.jpg",
    desc: `Chapati, also known as roti, rotli, safati, shabaati, phulka, chapo, and roshi, is an unleavened flatbread `,
  },
  {
    id: 5,
    title: "Sausages",
    category: "Snacks",
    price: 40,
    img: "./images/sausages.jfif",
    desc: `Type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings.  `,
  },
  {
    id: 6,
    title: "Smokies",
    category: "Snacks",
    price: 30,
    img: "./images/smokies.jfif",
    desc: `Type of ready- to- eat smoked sausage that can be made of pork, beef, chicken or a blend of all these meats and other flavourful inclusions`,
  },
  {
    id: 7,
    title: "Viazi Karai",
    category: "Snacks",
    price: 10,
    img: "./images/viazikarai.jpg",
    desc: `deep fried potatoes dipped in Gram Flour mixture and turmeric or you can use yellow food color`,
  },
  {
    id: 8,
    title: "Omelet",
    category: "Snacks",
    price: 50,
    img: "./images/omelet.jpg",
    desc: `dish made from beaten eggs, fried with butter or oil in a frying pan. `,
  },
  {
    id: 9,
    title: "Chapati Spanish Rolex",
    category: "Snacks",
    price: 70,
    img: "./images/rolex.jpg",
    desc: `a rolled chapati containing a fried egg, vegetables, minced meat or chicken chunks`,
  },
  {
    id: 10,
    title: "French fries (Chips)",
    category: "Snacks",
    price: 100,
    img: "./images/chips.jpg",
    desc: `batonnet or allumette-cut deep-fried potatoes`,
  },
  {
    id: 11,
    title: "Bhanjias",
    category: "Snacks",
    price: 120,
    img: "./images/bhanjias.jfif",
    desc: `excellent appetizers and finger foods or even as a main dish`,
  },
  {
    id: 12,
    title: "Hot dogs",
    category: "Snacks",
    price: 50,
    img: "./images/hotdog.jfif",
    desc: `a grilled or steamed sausage served in the slit of a partially sliced bun`,
  },
  {
    id: 13,
    title: "Burgers",
    category: "Snacks",
    price: 100,
    img: "./images/burgers.jfif",
    desc: `a sandwich, consisting of one or more cooked patties`,
  },
  {
    id: 14,
    title: "Tea",
    category: "Drinks",
    price: 30,
    img: "./images/tea.jfif",
    desc: `a drink made by adding hot water to tea leaves or tea bags and milk`,
  },
  {
    id: 15,
    title: "Dawa",
    category: "Drinks",
    price: 60,
    img: "./images/dawa.jfif",
    desc: `a concoction of honey, lemon, ginger, and turmeric`,
  },
  {
    id: 16,
    title: "Black Coffee",
    category: "Drinks",
    price: 50,
    img: "./images/blackcoffee.jpg",
    desc: `beverage made from roasted coffee beans`,
  },
  {
    id: 17,
    title: "White Coffee",
    category: "Drinks",
    price: 60,
    img: "./images/whitecoffee.jpg",
    desc: `A flat white is a coffee drink consisting of espresso with microfoam`,
  },
  {
    id: 18,
    title: "White CHOCHOLATE",
    category: "Drinks",
    price: 60,
    img: "./images/whitechocolate.jfif",
    desc: ` a rich and creamy decadent drink `,
  },
  {
    id: 19,
    title: "Dark chocholate",
    category: "Drinks",
    price: 50,
    img: "./images/darkchocolate.jfif",
    desc: `Creamy, thick drinking chocolate`,
  },
  {
    id: 20,
    title: "Plain Milk ( Pouch)",
    category: "Drinks",
    price: 60,
    img: "./images/milk.jpeg",
    desc: `Plain milk pouch`,
  },
  {
    id: 21,
    title: "Porridge",
    category: "Drinks",
    price: 40,
    img: "./images/porridge.jfif",
    desc: `made by heating or boiling ground, crushed or chopped starchy plants, typically grain, in milk or water.`,
  },
  {
    id: 22,
    title: "Water",
    category: "Drinks",
    price: 40,
    img: "./images/water.jfif",
    desc: `bottled drinking water`,
  },
  {
    id: 23,
    title: "Juices",
    category: "Drinks",
    price: 50,
    img: "./images/juices.jfif",
    desc: `from the extraction or pressing of the natural liquid contained in fruit and vegetables`,
  },
  {
    id: 24,
    title: "Soda",
    category: "Drinks",
    price: 50,
    img: "./images/soda.jpg",
    desc: `Carbonated drinks`,
  },
  {
    id: 25,
    title: "Yoghurt",
    category: "Drinks",
    price: 60,
    img: "./images/yoghurt.jfif",
    desc: `produced by bacterial fermentation of milk`,
  },
  {
    id: 26,
    title: "Beef Stew",
    category: "Meals",
    price: 120,
    img: "./images/beefstew.jfif",
    desc: `combination of vegetables and meat`,
  },
  {
    id: 27,
    title: "Melz Coconut beans",
    category: "Meals",
    price: 80,
    img: "./images/beans.jfif",
    desc: `coconut beans`,
  },
  {
    id: 28,
    title: "Assorted Veggies",
    category: "Meals",
    price: 80,
    img: "./images/vegges.jfif",
    desc: `Assorted Veggies`,
  },
  {
    id: 29,
    title: "Pilau",
    category: "Meals",
    price: 120,
    img: "./images/pilau.jfif",
    desc: `rice soaked in stock or broth, adding meat, spices, and other ingredients such as vegetables`,
  },
  {
    id: 30,
    title: "Matoke",
    category: "Meals",
    price: 60,
    img: "./images/matoke.jpeg",
    desc: `cooked banana`,
  },
  {
    id: 31,
    title: "Mukimo",
    category: "Meals",
    price: 70,
    img: "./images/mukimo.jpeg",
    desc: `Mashed potatoes`,
  },
];
export default menu;
